"""empty message

Revision ID: 56d83525479a
Revises: cb4f3cfbbe1c
Create Date: 2022-03-25 12:54:12.541056

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56d83525479a'
down_revision = 'cb4f3cfbbe1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('thread_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['thread_id'],
                        ['thread.id'],
                    ), sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['user.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    # ### end Alembic commands ###
