"""empty message

Revision ID: cb4f3cfbbe1c
Revises: cc4cb9f410b7
Create Date: 2022-03-24 12:49:23.137886

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb4f3cfbbe1c'
down_revision = 'cc4cb9f410b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=30), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    # ### end Alembic commands ###
